// app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AbhayaAssignment",
  description: "Generated by Abhaya",
  keywords: "portfolio, technology, APIs, blog, web development",
  author: "Abhaya",
  location: "Global",
  language: "en",
  og: {
    title: "Abhaya's Portfolio",
    description: "Explore my projects and blog on technology.",
    image: "/images/og-image.png", // Replace with your Open Graph image
    url: "https://your-portfolio-url.com"
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
